DigitalOcean test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,92 +27,91 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
-      - name: Upgrade AWS CLI version and setup lightsailctl
-        run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
-          which aws
-          aws --version
-          sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
-          sudo chmod +x /usr/local/bin/lightsailctl
 
-      - name: Build, tag, and push Docker image
+      - name: Install doctl 
+        uses: digitalocean/action-doctl@v2
+        with:
+          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
+
+      - name: Build docker image
         id: build-image
         run: |
           IMAGE_TAG=latest
           docker build \
           --build-arg SECRET = {{ secrets.SECRET }} \
           -t inhousechef-api:$IMAGE_TAG ./src/Weather -f ./src/Weather/Services/WebApi/Dockerfile \
-          
-          aws lightsail push-container-image --region eu-central-1 --service-name my-api --label inhousechef-api --image inhousechef-api:$IMAGE_TAG
-        env:
-          AWS_REGION: eu-central-1
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build
+      - name: Build container image
+        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest ./src/Weather -f ./src/Weather/Services/WebApi/Dockerfile
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - name: Log in to DigitalOcean Container Registry with short-lived credentials
+        run: doctl registry login --expiry-seconds 600
 
-      - name: Upgrade AWS CLI version and setup lightsailctl
-        run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
-          which aws
-          aws --version
-          sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
-          sudo chmod +x /usr/local/bin/lightsailctl
+      - name: Push image to DigitalOcean Container Registry
+        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
 
-      - name: Install jq
-        run: sudo apt-get install jq
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   needs: build
 
-      - name: Create new Lightsail deployment
-        id: create-deployment
-        run: |
-          IMAGE_TAG=$(aws lightsail get-container-images --service my-api --region eu-central-1 | jq -r .containerImages[0].image)
-          echo "Deploying $IMAGE_TAG image..."
-          aws lightsail create-container-service-deployment --service-name my-api \
-           --containers "{
-              \"inhousechef-backend\": {
-                \"image\": \"$IMAGE_TAG\",
-                \"environment\": {
-                },
-                \"ports\": {
-                  \"8080\": \"HTTP\",
-                  \"10000\": \"HTTP\"
-                }
-              }
-            }" \
-          --public-endpoint file://Lightsail/public-endpoint.json
-        env:
-          AWS_REGION: eu-central-1
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - name: Check deployment status
-        run: |
-          for i in {1..100}; do
-            DEPLOYMENT_STATUS=$(aws lightsail get-container-service-deployments --service-name my-api --region eu-central-1 --query 'deployments[0].state' --output text)
-            if [ "$DEPLOYMENT_STATUS" = "ACTIVE" ]; then
-              echo "Deployment succeeded"
-              exit 0
-            elif [ "$DEPLOYMENT_STATUS" = "FAILED" ]; then
-              echo "Deployment failed"
-              exit 1
-            else
-              echo "Deployment status: $DEPLOYMENT_STATUS"
-              sleep 10
-            fi
-          done
-          echo "Deployment timed out"
-          exit 1
-        env:
-          AWS_REGION: eu-central-1
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #     - name: Upgrade AWS CLI version and setup lightsailctl
+  #       run: |
+  #         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+  #         unzip awscliv2.zip
+  #         sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
+  #         which aws
+  #         aws --version
+  #         sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
+  #         sudo chmod +x /usr/local/bin/lightsailctl
+
+  #     - name: Install jq
+  #       run: sudo apt-get install jq
+
+  #     - name: Create new Lightsail deployment
+  #       id: create-deployment
+  #       run: |
+  #         IMAGE_TAG=$(aws lightsail get-container-images --service my-api --region eu-central-1 | jq -r .containerImages[0].image)
+  #         echo "Deploying $IMAGE_TAG image..."
+  #         aws lightsail create-container-service-deployment --service-name my-api \
+  #          --containers "{
+  #             \"inhousechef-backend\": {
+  #               \"image\": \"$IMAGE_TAG\",
+  #               \"environment\": {
+  #               },
+  #               \"ports\": {
+  #                 \"8080\": \"HTTP\",
+  #                 \"10000\": \"HTTP\"
+  #               }
+  #             }
+  #           }" \
+  #         --public-endpoint file://Lightsail/public-endpoint.json
+  #       env:
+  #         AWS_REGION: eu-central-1
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
+  #     - name: Check deployment status
+  #       run: |
+  #         for i in {1..100}; do
+  #           DEPLOYMENT_STATUS=$(aws lightsail get-container-service-deployments --service-name my-api --region eu-central-1 --query 'deployments[0].state' --output text)
+  #           if [ "$DEPLOYMENT_STATUS" = "ACTIVE" ]; then
+  #             echo "Deployment succeeded"
+  #             exit 0
+  #           elif [ "$DEPLOYMENT_STATUS" = "FAILED" ]; then
+  #             echo "Deployment failed"
+  #             exit 1
+  #           else
+  #             echo "Deployment status: $DEPLOYMENT_STATUS"
+  #             sleep 10
+  #           fi
+  #         done
+  #         echo "Deployment timed out"
+  #         exit 1
+  #       env:
+  #         AWS_REGION: eu-central-1
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
